# Github Actions Workflow file that builds and pushes the docker images.
name: practicalgitops.app
env:
  DOCKERHUB_TAG: "${{ secrets.DOCKERHUB_USERNAME }}/practicalgitops"
  DOCKERFILE_PATH: app
  VERSION: latest

on:
  push:
    branches: [ "dev**", "staging**", "main**", "prod**", "uat**", "preprod**" ]
    paths: [ "app/**", "!**/README.md", "!**/LICENSE", ".github/workflows/app.yaml"]

  release:
    types: [ created ]

permissions:
  contents: write
  issues: write
  pull-requests: write

# Job declaration starts.
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      
      - name: Get the release version
        #id: get_version
        run: |
            if [ ${{ github.event_name }} == 'release' ]; then       
               echo "RELEASE_VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
            else
               echo "RELEASE_VERSION=${{ env.VERSION }}" >> $GITHUB_ENV
            fi

      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: "${{ env.DOCKERFILE_PATH }}"
          push: true
          tags: "${{ env.DOCKERHUB_TAG }}:${{ env.RELEASE_VERSION }}"
            